{{- if and .Values.keycloak.enabled .Values.keycloak.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "glpi-sso.fullname" . }}-keycloak
  labels:
    {{- include "glpi-sso.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.keycloak.persistence.storageClass }}
  storageClassName: {{ .Values.keycloak.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.keycloak.persistence.size | quote }}
{{- end }}
