{{- if .Values.oauth2-proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "glpi-sso.fullname" . }}-oauth2-proxy
  labels:
    {{- include "glpi-sso.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  type: {{ .Values.oauth2-proxy.service.type }}
  ports:
    - port: {{ .Values.oauth2-proxy.service.port }}
      targetPort: {{ .Values.oauth2-proxy.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "glpi-sso.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
{{- end }}
