{{- $v := .Values -}}
  {{- if and (index $v "oauth2-proxy" "enabled") (index $v "oauth2-proxy" "ingress" "enabled") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "glpi-sso.fullname" . }}-oauth2-proxy
  labels:
    {{- include "glpi-sso.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  {{- $ing := (index $v "oauth2-proxy" "ingress") -}}
    {{- with (index $ing "className") }}
    ingressClassName: {{ . }}
    {{- end }}
    {{- if (index $ing "tls") }}
    tls:
      {{- range (index $ing "tls") }}
      - hosts:
          {{- range .hosts }}
          - {{ . | quote }}
          {{- end }}
        secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
    rules:
      {{- range (index $ing "hosts") }}
      - host: {{ .host | quote }}
        http:
          paths:
            {{- range .paths }}
            - path: {{ .path | quote }}
              pathType: {{ .pathType | default "Prefix" }}
              backend:
                service:
                  name: {{ include "glpi-sso.fullname" $ }}-oauth2-proxy
                  port:
                    number: {{ (index $v "oauth2-proxy" "service" "port") | default 4180 }}
            {{- end }}
      {{- end }}
  {{- end }}