{{- if (index .Values "oauth2-proxy" "enabled") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "glpi-sso.fullname" . }}-oauth2-proxy
  labels:
    {{- include "glpi-sso.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  type: {{ (index .Values "oauth2-proxy" "service" "type") | default "ClusterIP" }}
  ports:
    - port: {{ (index .Values "oauth2-proxy" "service" "port") | default 4180 }}
      targetPort: {{ (index .Values "oauth2-proxy" "service" "targetPort") | default 4180 }}
      protocol: TCP
      name: http
  selector:
    {{- include "glpi-sso.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
  {{- end }}