# kind.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sso
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            service-node-port-range: "80-32767"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: Tkubectl -n ingress-nginx describe pod ingress-nginx-controller-84c86f987b-z9lhkCP